m=require("aoy")
-- require "io"
--[[
file = io.open ("shell.go","r")
io.input(file)
print(io.read())
print(io.read())
print(io.read())
print("hello worker!")
print("aoy!")
print("I am hobbit!")
print(m)
s,e=m.http_get("http://www.baidu.com")
print(s)
print("--------------")
print(m.html_doc("http://www.baidu.com"))
print(m.html_find("div#s_qrcode_nologin"))
print(m.html_text())
print(m.html_find("div.s_tab_inner"))
print(m.html_text())
arrays=m.html_attr("href")
print(arrays[1])
print("--------------")
--print(e)
--]]
--m.os_run("C:\\Program Files\\Notepad++\\notepad++.exe",{""})
--print(m.os_cmd("dir",{"c:"}))
print("hello task run")
print(_inputs.url)
_records.result="yes"
print(_records.result)